name: Publish npm

on:
  push:
    tags:
      - v*

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11.7.0

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build:core

      - name: Publish to npm
        run: pnpm publish --access public --no-git-checks --provenance --filter @easy-vite/plugin-html
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
