name: Create Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            Please refer to [CHANGELOG.md](https://github.com/easy-vite/plugin-html/blob/main/CHANGELOG.md) for details.
